### PR TITLE
Grammar fixes

### PR DESCRIPTION
**Pull request by Dark42ed**
Just fixes some grammar in the docs

### CODE REVIEW

**Review by Darkflame72 — CHANGES_REQUESTED** [review]
Looks good so far, would you be able to look through the rest of the docs/docstrings and see if there is anything that can be fixed in there?

**Comment by Dark42ed** [comment]
Sure

**Comment by Darkflame72** [comment]
@all-contributors please add @Dark42ed for docs

**Comment by Dark42ed** [comment]
Docstrings look good. Fixed everything I could find in the docs.

**Comment by Dark42ed** [comment]
[version_guarantees.rst](https://github.com/Darkflame72/defectio/blob/main/docs/version_guarantees.rst) has statements about lack of guarantees from discord. Would it be best to remove it? I'm sure the statements don't apply to revolt.

**Comment by Dark42ed** [comment]
Looks good for merge. Can't find anything else to change.

**Review by Darkflame72 — APPROVED** [review]

**Pull request merged**
